codon_list = [None] * 61
codon_list[0] = "AAA"
codon_list[1] = "AAC"
codon_list[2] = "AAG"
codon_list[3] = "AAU"
codon_list[4] = "ACA"
codon_list[5] = "ACC"
codon_list[6] = "ACG"
codon_list[7] = "ACU"
codon_list[8] = "AGA"
codon_list[9] = "AGC"
codon_list[10] = "AGG"
codon_list[11] = "AGU"
codon_list[12] = "AUA"
codon_list[13] = "AUC"
codon_list[14] = "AUG"
codon_list[15] = "AUU"
codon_list[16] = "CAA"
codon_list[17] = "CAC"
codon_list[18] = "CAG"
codon_list[19] = "CAU"
codon_list[20] = "CCA"
codon_list[21] = "CCC"
codon_list[22] = "CCG"
codon_list[23] = "CCU"
codon_list[24] = "CGA"
codon_list[25] = "CGC"
codon_list[26] = "CGG"
codon_list[27] = "CGU"
codon_list[28] = "CUA"
codon_list[29] = "CUC"
codon_list[30] = "CUG"
codon_list[31] = "CUU"
codon_list[32] = "GAA"
codon_list[33] = "GAC"
codon_list[34] = "GAG"
codon_list[35] = "GAU"
codon_list[36] = "GCA"
codon_list[37] = "GCC"
codon_list[38] = "GCG"
codon_list[39] = "GCU"
codon_list[40] = "GGA"
codon_list[41] = "GGC"
codon_list[42] = "GGG"
codon_list[43] = "GGU"
codon_list[44] = "GUA"
codon_list[45] = "GUC"
codon_list[46] = "GUG"
codon_list[47] = "GUU"
# UAA is a stop codon
codon_list[48] = "UAC"
# UAG is a stop codon
codon_list[49] = "UAU"
codon_list[50] = "UCA"
codon_list[51] = "UCC"
codon_list[52] = "UCG"
codon_list[53] = "UCU"
# UGA is a stop codon
codon_list[54] = "UGC"
codon_list[55] = "UGG"
codon_list[56] = "UGU"
codon_list[57] = "UUA"
codon_list[58] = "UUC"
codon_list[59] = "UUG"
codon_list[60] = "UUU"

def get_codon_num(codon_string):
    try:
        return codon_list.index(codon_string)
    except ValueError:
        return -1   # stop codon

def get_codon_string(codon_num):
    return codon_list[codon_num]
